// SPDX-FileCopyrightText: 2026 luminescq
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `into`

Stream<String> setupLogStream() =>
    RustLib.instance.api.crateApiSimpleSetupLogStream();

Future<void> stopCsqttClient() =>
    RustLib.instance.api.crateApiSimpleStopCsqttClient();

/// [FOCSQ] Путь к wintun.dll, распакованному Flutter-стороной
/// в %LOCALAPPDATA%\FOCSQ — паттерн WireGuard/Amnezia.
Future<void> setWintunDllPath({required String path}) =>
    RustLib.instance.api.crateApiSimpleSetWintunDllPath(path: path);

/// Команда управления ядром ("PAUSE", "RESUME", "PATH_VALIDATE:", "CAPTCHA_RESULT|...")
Future<bool> sendControlCommand({required String command}) =>
    RustLib.instance.api.crateApiSimpleSendControlCommand(command: command);

/// Пауза/возобновление обработки трафика воркерами
Future<bool> setClientPaused({required bool paused}) =>
    RustLib.instance.api.crateApiSimpleSetClientPaused(paused: paused);

/// Передать результат решения WebView-капчи в ядро (success_token или "error:...")
Future<bool> submitCaptchaResult({required String result}) =>
    RustLib.instance.api.crateApiSimpleSubmitCaptchaResult(result: result);

Future<void> startCsqttClient({required AppClientConfig config}) =>
    RustLib.instance.api.crateApiSimpleStartCsqttClient(config: config);

class AppClientConfig {
  final String turn;
  final String port;
  final String listen;
  final String vk;
  final String vkHashMode;
  final String peer;
  final BigInt workers;
  final bool allowHashRedistribution;
  final String deviceId;
  final String password;
  final String vkAuthMode;
  final String captchaMode;
  final String fingerprint;
  final String clientIds;
  final String obfs;
  final BigInt generation;
  final String salt;
  final String tunUds;
  final bool validateVkHashes;
  final String vkJsToken;

  const AppClientConfig({
    required this.turn,
    required this.port,
    required this.listen,
    required this.vk,
    required this.vkHashMode,
    required this.peer,
    required this.workers,
    required this.allowHashRedistribution,
    required this.deviceId,
    required this.password,
    required this.vkAuthMode,
    required this.captchaMode,
    required this.fingerprint,
    required this.clientIds,
    required this.obfs,
    required this.generation,
    required this.salt,
    required this.tunUds,
    required this.validateVkHashes,
    required this.vkJsToken,
  });

  @override
  int get hashCode =>
      turn.hashCode ^
      port.hashCode ^
      listen.hashCode ^
      vk.hashCode ^
      vkHashMode.hashCode ^
      peer.hashCode ^
      workers.hashCode ^
      allowHashRedistribution.hashCode ^
      deviceId.hashCode ^
      password.hashCode ^
      vkAuthMode.hashCode ^
      captchaMode.hashCode ^
      fingerprint.hashCode ^
      clientIds.hashCode ^
      obfs.hashCode ^
      generation.hashCode ^
      salt.hashCode ^
      tunUds.hashCode ^
      validateVkHashes.hashCode ^
      vkJsToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppClientConfig &&
          runtimeType == other.runtimeType &&
          turn == other.turn &&
          port == other.port &&
          listen == other.listen &&
          vk == other.vk &&
          vkHashMode == other.vkHashMode &&
          peer == other.peer &&
          workers == other.workers &&
          allowHashRedistribution == other.allowHashRedistribution &&
          deviceId == other.deviceId &&
          password == other.password &&
          vkAuthMode == other.vkAuthMode &&
          captchaMode == other.captchaMode &&
          fingerprint == other.fingerprint &&
          clientIds == other.clientIds &&
          obfs == other.obfs &&
          generation == other.generation &&
          salt == other.salt &&
          tunUds == other.tunUds &&
          validateVkHashes == other.validateVkHashes &&
          vkJsToken == other.vkJsToken;
}
